### PR TITLE
initial commit motorpair

### PR DESCRIPTION
**Pull request by justintangwh**
check if the logic is correct or not im not too sure

### CODE REVIEW

**Review by Eisverygoodletter — CHANGES_REQUESTED** [review]
Did you read about classes on w3schools.com

**Comment by justintangwh** [comment]
yes

**Comment by Eisverygoodletter** [comment]
Only constructor takes in motors and the stores them inside the class

**Review by txvvgnx — CHANGES_REQUESTED** [review]
- Change the semicolon from the end of namespace declaration to the end of class declaration
- Remove Ev3Wrap::Motor inheritance (not necessary) 
- Remove RPM parameter from MotorPair constructor, RPM is determined by the user when they run the motor pair (MotorPair->move())
- Remove motor1 and motor2 parameters from move and stop functions, as you have already declared them earlier in the class and defined them when the constructor is called

**Review by txvvgnx — CHANGES_REQUESTED** [review]
Almost done:
- Create function to construct MotorPair (basically a function that calls the constructor and returns the class object)
- Add RPM back to move function

**Review by txvvgnx — CHANGES_REQUESTED** [review]
Change the function on line 21-25 of ev3wrapmotorpair.cpp to CreateMotorPair and add CreateMotorPair to the function list in the header file. Currently the function on line 21-25 is just a rewrite of the constructor and wouldn't work since constructors don't specify return types

**Review by txvvgnx — APPROVED** [review]

**Comment by txvvgnx** [comment]
Note: There was a weird error that occurred due to the motor constructor being private (?) but it's fixed now (maybe because I changed the vars to static)

**Comment by Eisverygoodletter** [comment]
merge ready?

**Comment by txvvgnx** [comment]
yes

**Review by Eisverygoodletter — APPROVED** [review]
Looks much better now

**Pull request merged**
