### PR TITLE
Created color sensor wrapper library

### PR DESCRIPTION
**Pull request by txvvgnx**
Review code pls 
also I fixed a dumb issue where I did ifndef ULTRASONICHPP instead of COMPASSHPP

### CODE REVIEW

**Review by Eisverygoodletter — COMMENTED** [review]
Make get colour return an enum class instead of an int. this is more readable and enum class elements can correspond to int s.

**Comment by txvvgnx** [comment]
@Eisverygoodletter can you check if I'm using this correctly or not

**Comment by Eisverygoodletter** [comment]
No there's a simpler way. Let's try not to resort to type-casting

**Comment by Eisverygoodletter** [comment]
ok you know what I would allow static_cast<>()  here. However, with `enum class` syntax you can do
```cpp
enum class Color {
    NONE = 0,
    BLACK = 1,
    BLUE = 2,
    GREEN = 3,
    YELLOW = 4,
    RED = 5,
    WHITE = 6,
    BROWN = 7
};
```
to be more expressive on what they actually represent

**Comment by Eisverygoodletter** [comment]
am doing the compile test right now

**Review by Eisverygoodletter — APPROVED** [review]
ok it's good

**Pull request merged**
